#
#  Copyright OpenSearch Contributors
#  SPDX-License-Identifier: Apache-2.0
#

version=0.1.0
opensearch_version=3.7.0
lance_core_version=12.0.0
lance_namespace_version=0.11.1
lance_namespace_impls_version=0.4.1
httpclient5_version=5.2.1
httpcore5_version=5.2
aws_sdk_version=2.32.2
aws_eventstream_version=1.0.1
arrow_version=18.3.0
jackson_databind_version=2.21.3
jackson_annotations_version=2.21
flatbuffers_version=2.0.0
slf4j_version=2.0.17
commons_codec_version=1.18.0
questdb_jar_jni_version=1.1.1
calcite_version=1.39.0
avatica_version=1.26.0
janino_version=3.1.11
jsonpath_version=2.9.0
substrait_version=0.57.0
guava_version=33.3.0-jre
failureaccess_version=1.0.2
java_release_version=21
