/*
 * Copyright OpenSearch Contributors
 * SPDX-License-Identifier: Apache-2.0
 */

package org.opensearch.lance.plan.translate;

import com.carrotsearch.randomizedtesting.annotations.Name;
import com.carrotsearch.randomizedtesting.annotations.ParametersFactory;
import org.opensearch.test.OpenSearchTestCase;

import java.io.IOException;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.List;

/**
 * Pins the translation of every supported aggregation shape to its
 * exact plan text. Each fixture is a search body
 * ({@code translate/aggregations/<name>.json}) next to the
 * {@code RelOptUtil.toString} output of its translation
 * ({@code <name>.plan}); the plan files were generated by running the
 * translator once and hand checked against the request bodies, so a
 * change in this test is a change in what a request plans to.
 */
public class AggregationToRelFixtureTests extends OpenSearchTestCase {

    /** One fixture per shape family the translator supports. */
    static final List<String> FIXTURES = List.of(
        "metric_sum",
        "metric_stats",
        "metric_extended_stats",
        "metric_cardinality",
        "metric_percentiles",
        "metric_percentile_ranks",
        "terms_count_desc",
        "terms_key_asc",
        "terms_sub_agg_order",
        "histogram",
        "date_histogram_fixed",
        "date_histogram_calendar_month",
        "range",
        "date_range",
        "filter",
        "filters_with_other",
        "missing",
        "nested_terms_terms_avg",
        "nested_terms_date_histogram_sum",
        "composite_terms_date_histogram",
        "composite_with_after",
        "two_metric_only_aggs",
        "query_term_terms"
    );

    private final String fixture;

    public AggregationToRelFixtureTests(@Name("fixture") String fixture) {
        this.fixture = fixture;
    }

    @ParametersFactory
    public static Iterable<Object[]> fixtures() {
        List<Object[]> parameters = new ArrayList<>(FIXTURES.size());
        for (String name : FIXTURES) {
            parameters.add(new Object[] { name });
        }
        return parameters;
    }

    public void testTranslatesToThePinnedPlan() throws IOException {
        String body = resource(fixture + ".json");
        String actual = PlanTestFixtures.plan(PlanTestFixtures.parse(body));
        String expected;
        try {
            expected = resource(fixture + ".plan");
        } catch (IOException missing) {
            throw new AssertionError("missing plan fixture for [" + fixture + "]; the translator produced:\n" + actual, missing);
        }
        assertEquals("plan of fixture [" + fixture + "]", expected, actual);
    }

    /** The text of one fixture file under {@code translate/aggregations/}. */
    static String resource(String name) throws IOException {
        String path = "/translate/aggregations/" + name;
        try (InputStream in = AggregationToRelFixtureTests.class.getResourceAsStream(path)) {
            if (in == null) {
                throw new IOException("resource not found: " + path);
            }
            return new String(in.readAllBytes(), StandardCharsets.UTF_8);
        }
    }
}
