/*
 * Copyright OpenSearch Contributors
 * SPDX-License-Identifier: Apache-2.0
 */

package org.opensearch.lance.plan.translate;

import com.carrotsearch.randomizedtesting.annotations.Name;
import com.carrotsearch.randomizedtesting.annotations.ParametersFactory;
import org.apache.calcite.plan.RelOptUtil;
import org.apache.calcite.rel.RelNode;
import org.opensearch.lance.plan.calcite.LanceSchemas;
import org.opensearch.lance.plan.rel.LanceFtsMatch;
import org.opensearch.lance.plan.rel.LanceKnnSearch;
import org.opensearch.search.builder.SearchSourceBuilder;
import org.opensearch.test.OpenSearchTestCase;

import java.io.IOException;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.List;

/**
 * Pins the translation of every supported full text and knn query
 * shape to the exact logical plan it produces over the fixture row
 * type, one fixture per shape with and without a scalar filter. Each
 * fixture is a search body carrying only the query
 * ({@code translate/queries/fts/<name>.json} /
 * {@code .../knn/<name>.json}) next to the
 * {@link RelOptUtil#toString} text of its plan ({@code <name>.plan});
 * a fixture whose plan file starts with {@code error: } pins the
 * refusal message instead. The plan files were generated by running
 * the translator once and hand checked against the request bodies.
 */
public class LanceQueryShapeFixtureTests extends OpenSearchTestCase {

    /** One fixture per FTS shape (bare and filtered) and per refusal. */
    public static final List<String> FTS_FIXTURES = List.of(
        "match",
        "match_boosted",
        "match_bare_bool",
        "match_filtered",
        "match_must_not_only",
        "match_phrase",
        "match_phrase_filtered",
        "multi_match",
        "multi_match_filtered",
        "fts_bool",
        "fts_bool_filtered",
        "fts_boost",
        "fts_boost_filtered",
        "refusal_fts_in_should",
        "refusal_fts_in_filter",
        "refusal_fts_in_must_not",
        "refusal_two_fts_in_must",
        "refusal_fts_with_scalar_must",
        "refusal_fts_with_knn",
        "refusal_bool_boost",
        "refusal_minimum_should_match",
        "refusal_filter_untranslatable",
        "refusal_filter_unmapped"
    );

    /** One fixture per knn shape (bare, tuned, filtered) and per refusal. */
    public static final List<String> KNN_FIXTURES = List.of(
        "knn",
        "knn_tuned",
        "knn_filtered",
        "knn_bool_filtered",
        "refusal_knn_in_bool",
        "refusal_knn_bad_filter",
        "refusal_knn_filter_unmapped"
    );

    private final String directory;
    private final String fixture;

    public LanceQueryShapeFixtureTests(@Name("directory") String directory, @Name("fixture") String fixture) {
        this.directory = directory;
        this.fixture = fixture;
    }

    @ParametersFactory
    public static Iterable<Object[]> fixtures() {
        List<Object[]> parameters = new ArrayList<>(FTS_FIXTURES.size() + KNN_FIXTURES.size());
        for (String name : FTS_FIXTURES) {
            parameters.add(new Object[] { "fts", name });
        }
        for (String name : KNN_FIXTURES) {
            parameters.add(new Object[] { "knn", name });
        }
        return parameters;
    }

    public void testTranslatesToThePinnedPlan() throws IOException {
        SearchSourceBuilder source = PlanTestFixtures.parse(resource(directory, fixture + ".json"));
        String actual;
        try {
            actual = RelOptUtil.toString(translateShape(source));
        } catch (UnsupportedOperationException refusal) {
            actual = "error: " + refusal.getMessage() + "\n";
        }
        String expected;
        try {
            expected = resource(directory, fixture + ".plan");
        } catch (IOException missing) {
            throw new AssertionError(
                "missing plan fixture for [" + directory + "/" + fixture + "]; the translator produced:\n" + actual,
                missing
            );
        }
        assertEquals("plan of fixture [" + directory + "/" + fixture + "]", expected, actual);
    }

    /** Translates a fixture body and asserts it becomes the FTS or knn node. */
    static RelNode translateShape(SearchSourceBuilder source) {
        LanceSchemas.IndexModel model = PlanTestFixtures.queryModel();
        RelNode node = SearchRequestToRel.translateQuery(source.query(), model, PlanTestFixtures.factory());
        assertTrue(
            "a non-refusal fixture translates to an FTS or knn node, saw " + node.getClass().getSimpleName(),
            node instanceof LanceFtsMatch || node instanceof LanceKnnSearch
        );
        return node;
    }

    /** Reads one fixture resource of {@code directory} ({@code fts} / {@code knn}). */
    public static String resource(String directory, String name) throws IOException {
        String path = "/translate/queries/" + directory + "/" + name;
        try (InputStream in = LanceQueryShapeFixtureTests.class.getResourceAsStream(path)) {
            if (in == null) {
                throw new IOException("resource not found: " + path);
            }
            return new String(in.readAllBytes(), StandardCharsets.UTF_8);
        }
    }
}
