/*
 * Copyright OpenSearch Contributors
 * SPDX-License-Identifier: Apache-2.0
 */

package org.opensearch.lance.plan.translate;

import com.carrotsearch.randomizedtesting.annotations.Name;
import com.carrotsearch.randomizedtesting.annotations.ParametersFactory;
import org.apache.calcite.rex.RexNode;
import org.apache.calcite.tools.RelBuilder;
import org.opensearch.lance.plan.calcite.LancePlannerFactory;
import org.opensearch.lance.plan.calcite.LanceSchemas;
import org.opensearch.search.builder.SearchSourceBuilder;
import org.opensearch.test.OpenSearchTestCase;

import java.io.IOException;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.List;

/**
 * Pins the translation of every supported query shape to the exact
 * {@link RexNode} digest it produces over the fixture row type, one
 * fixture per query type and field kind. Each fixture is a search body
 * carrying only the query ({@code translate/queries/<name>.json}) next
 * to the digest of its predicate ({@code <name>.plan}); a fixture whose
 * plan file starts with {@code error: } pins the refusal message
 * instead. The plan files were generated by running the translator once
 * and hand checked against the request bodies.
 */
public class QueryToRexFixtureTests extends OpenSearchTestCase {

    /** One fixture per query type and field kind the translator supports or refuses. */
    static final List<String> FIXTURES = List.of(
        "match_all",
        "match_none",
        "term_keyword",
        "term_integer",
        "term_float",
        "term_boolean",
        "term_timestamp",
        "term_date_day",
        "term_struct_child",
        "term_multi_field",
        "term_unmapped",
        "terms_keyword",
        "terms_integer",
        "terms_empty",
        "exists",
        "exists_struct_child",
        "range_integer",
        "range_float",
        "range_timestamp",
        "range_timestamp_format",
        "range_date_day",
        "range_struct_child",
        "bool_full",
        "bool_pure_should",
        "bool_must_not_only",
        "wildcard",
        "wildcard_case_insensitive",
        "regexp",
        "regexp_case_insensitive",
        "prefix",
        "prefix_case_insensitive",
        "ids",
        "wildcard_on_integer",
        "minimum_should_match",
        "query_type_match",
        "struct_path_unresolved"
    );

    private final String fixture;

    public QueryToRexFixtureTests(@Name("fixture") String fixture) {
        this.fixture = fixture;
    }

    @ParametersFactory
    public static Iterable<Object[]> fixtures() {
        List<Object[]> parameters = new ArrayList<>(FIXTURES.size());
        for (String name : FIXTURES) {
            parameters.add(new Object[] { name });
        }
        return parameters;
    }

    public void testTranslatesToThePinnedPredicate() throws IOException {
        SearchSourceBuilder source = PlanTestFixtures.parse(resource(fixture + ".json"));
        String actual;
        try {
            actual = predicate(source).toString();
        } catch (UnsupportedOperationException refusal) {
            actual = "error: " + refusal.getMessage();
        }
        String expected;
        try {
            expected = resource(fixture + ".plan").trim();
        } catch (IOException missing) {
            throw new AssertionError("missing plan fixture for [" + fixture + "]; the translator produced:\n" + actual, missing);
        }
        assertEquals("predicate of fixture [" + fixture + "]", expected, actual);
    }

    static RexNode predicate(SearchSourceBuilder source) {
        LanceSchemas.IndexModel model = PlanTestFixtures.queryModel();
        RelBuilder relBuilder = PlanTestFixtures.factory().relBuilder(model.schema()).transform(config -> config.withSimplify(false));
        relBuilder.scan(LancePlannerFactory.SCHEMA_NAME, model.indexName());
        return QueryToRex.translate(source.query(), model, relBuilder);
    }

    private String resource(String name) throws IOException {
        String path = "/translate/queries/" + name;
        try (InputStream in = QueryToRexFixtureTests.class.getResourceAsStream(path)) {
            if (in == null) {
                throw new IOException("resource not found: " + path);
            }
            return new String(in.readAllBytes(), StandardCharsets.UTF_8);
        }
    }
}
